### ISSUE TITLE
NoMethodError if underling kitchen log has an error

### ISSUE THREAD

**Issue by boc-tothefuture** [boc-tothefuture/kitchen-blame#1]
This log entry: 
```
E, [2017-07-05T08:31:22.995680 #27103] ERROR -- cloud-default-RHEL7: Message: SSH exited (1) for command: [sh -c '
TEST_KITCHEN="1"; export TEST_KITCHEN
BUSSER_ROOT="/tmp/verifier"; export BUSSER_ROOT
GEM_HOME="/tmp/verifier/gems"; export GEM_HOME
GEM_PATH="/tmp/verifier/gems"; export GEM_PATH
GEM_CACHE="/tmp/verifier/gems/cache"; export GEM_CACHE

sudo -E /tmp/verifier/bin/busser test
']
```
Causes this error
```
kitchen_blame.rb:25:in `extract_time': undefined method `[]' for nil:NilClass (NoMethodError)
	from /home/boc/.chefdk/gem/ruby/2.1.0/gems/kitchen_blame-0.2.0/lib/kitchen_blame.rb:94:in `block in analyze_duration'
	from /home/boc/.chefdk/gem/ruby/2.1.0/gems/kitchen_blame-0.2.0/lib/kitchen_blame.rb:91:in `map'
	from /home/boc/.chefdk/gem/ruby/2.1.0/gems/kitchen_blame-0.2.0/lib/kitchen_blame.rb:91:in `analyze_duration'
	from /home/boc/.chefdk/gem/ruby/2.1.0/gems/kitchen_blame-0.2.0/lib/kitchen_blame/cli.rb:34:in `duration'
	from /home/boc/.chefdk/gem/ruby/2.1.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /home/boc/.chefdk/gem/ruby/2.1.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/boc/.chefdk/gem/ruby/2.1.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /home/boc/.chefdk/gem/ruby/2.1.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /home/boc/.chefdk/gem/ruby/2.1.0/gems/kitchen_blame-0.2.0/exe/blame:19:in `<top (required)>'
	from /home/boc/.chefdk/gem/ruby/2.1.0/bin/blame:22:in `load'
	from /home/boc/.chefdk/gem/ruby/2.1.0/bin/blame:22:in `<main>'
```

**Comment by boc-tothefuture** [comment]
Resolved in 0.5.1
